# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    tasks: 'assembleRelease'

- task: AndroidSigning@3
  inputs:
   apkFiles: '**/*.apk'
   apksign: true
   apksignerKeystoreFile: 'keystore.jks'
   apksignerKeystorePassword: 'Mobile01'
   apksignerKeystoreAlias: 'HelloWorld'
   apksignerKeyPassword: 'Mobile01'
   apksignerArguments: --out $(Build.SourcesDirectory)/app/build/outputs/apk/release/app.release.apk
   zipalign: true

- task: CopyFiles@2
  inputs:
   SourceFolder: $(Build.SourcesDirectory)
   contents: '**/*.release.apk'
   targetFolder: '$(build.artifactStagingDirectory)'
   overWrite: true

- task: PublishBuildArtifacts@1
  inputs:
   pathtoPublish: '$(Build.ArtifactStagingDirectory)/app/build/outputs/apk/release/'
   artifactName: 'apks'
   publishLocation: 'container'